import test from 'node:test';
import assert from 'node:assert/strict';
import { openStore } from '../server/store.mjs';
import { createApi } from '../server/server.mjs';
import { effectiveCounts, monthlyAnalytics, nights, safeExternalUrl } from '../src/reservations/domain.ts';

const booking=(patch={})=>({source:'Airbnb',connectionId:'owner-connection',externalId:'booking-1',propertyId:'tiger-blvd-516',sourceUpdatedAt:'2026-09-01T00:00:00Z',guest:{displayName:'John Smith',externalId:'platform-user-1'},checkIn:'2026-09-10',checkOut:'2026-09-14',status:'confirmed',counts:{adults:2,children:2,infants:0,pets:1,totalHumanGuests:null},rawGuestCounts:{adults:2,children:2,infants:0,pets:1},stayRevenueCents:124500,currency:'USD',bookingUrl:'https://www.airbnb.com/',cleaningRequired:true,hotTubService:true,...patch});
const fixture=()=>{const store=openStore();const user=store.createUser('owner@example.test','a-long-test-password');return {store,user};};
test('actual humans include infants, exclude pets and produce exact guest nights',()=>{
 const {store,user}=fixture();try{const r=store.reservations.sync(user,booking());assert.equal(effectiveCounts(r).totalHumanGuests,4);const a=monthlyAnalytics([r],'2026-09');assert.equal(a.guestNights,16);assert.equal(a.counts.pets.known,1);const infant={...r,source:{...r.source,counts:{...r.source.counts,infants:1}}};assert.equal(effectiveCounts(infant).totalHumanGuests,5);assert.equal(monthlyAnalytics([infant],'2026-09').guestNights,20);}finally{store.close();}
});
test('missing is unknown, explicit zero is preserved, partial reporting exposes coverage',()=>{
 const {store,user}=fixture();try{const r=store.reservations.sync(user,booking({counts:{adults:2}}));assert.equal(effectiveCounts(r).totalHumanGuests,null);assert.equal(r.source.counts.infants,null);const a=monthlyAnalytics([r],'2026-09');assert.equal(a.averagePartySize,null);assert.equal(a.unknownGuestNights,4);assert.equal(a.counts.children.unknownStays,1);assert.equal(a.counts.adults.known,2);const total=store.reservations.override(user,r.id,{totalHumanGuests:4});assert.equal(monthlyAnalytics([total],'2026-09').guestNights,16);}finally{store.close();}
});
test('sync preserves original raw values, manual overrides, identity and audit snapshots',()=>{
 const {store,user}=fixture();try{const original=booking();const r=store.reservations.sync(user,original);store.reservations.override(user,r.id,{adults:3});const updated=store.reservations.sync(user,booking({counts:{adults:5,children:2,infants:0,pets:2,totalHumanGuests:7},sourceUpdatedAt:'2026-09-02T00:00:00Z'}));assert.equal(updated.id,r.id);assert.equal(updated.overrides.adults,3);assert.equal(effectiveCounts(updated).totalHumanGuests,5);const history=store.reservations.detail(user,r.id);assert.deepEqual(history.imports.at(-1).source,original);assert.equal(history.edits.length,1);assert.equal(history.imports.length,2);assert.equal(store.reservations.override(user,r.id,{}).overrides.adults,undefined);assert.throws(()=>store.reservations.sync(user,original),/Stale/);assert.throws(()=>store.reservations.override(user,r.id,{pets:-1}));}finally{store.close();}
});
test('unknown override masks source total; breakdown conflicts remain explicit',()=>{
 const source=booking({counts:{adults:2,children:2,infants:0,pets:1,totalHumanGuests:3}});assert.equal(effectiveCounts({source,overrides:{}}).conflict,true);assert.equal(effectiveCounts({source,overrides:{totalHumanGuests:null}}).totalHumanGuests,null);assert.equal(effectiveCounts({source,overrides:{infants:null}}).totalHumanGuests,null);
});
test('monthly attribution respects checkout, DST and cancellations',()=>{
 const {store,user}=fixture();try{const r=store.reservations.sync(user,booking({checkIn:'2026-09-29',checkOut:'2026-10-03'}));assert.equal(monthlyAnalytics([r],'2026-09').guestNights,8);const oct=monthlyAnalytics([r],'2026-10');assert.equal(oct.guestNights,8);assert.equal(oct.turnovers,1);assert.equal(monthlyAnalytics([r],'2026-09').turnovers,0);assert.equal(monthlyAnalytics([{...r,source:{...r.source,status:'cancelled'}}],'2026-09').stays,0);assert.equal(nights('2026-03-07','2026-03-10'),3);assert.equal(monthlyAnalytics([r,r],'2026-09').occupiedPropertyNights,2);}finally{store.close();}
});
test('guest reuse requires same stable platform identity and connection, never name alone',()=>{
 const {store,user}=fixture();try{const a=store.reservations.sync(user,booking());const repeat=store.reservations.sync(user,booking({externalId:'booking-2'}));assert.equal(a.guestId,repeat.guestId);const b=store.reservations.sync(user,booking({externalId:'booking-3',guest:{displayName:'John Smith'}}));const c=store.reservations.sync(user,booking({externalId:'booking-4',guest:{displayName:'John Smith'}}));assert.notEqual(b.guestId,c.guestId);const d=store.reservations.sync(user,booking({externalId:'booking-5',connectionId:'different-connection'}));assert.notEqual(a.guestId,d.guestId);const changed=store.reservations.sync(user,booking({externalId:'booking-3',guest:{displayName:'Jane Smith'},sourceUpdatedAt:'2026-09-02T00:00:00Z'}));assert.notEqual(changed.guestId,b.guestId);}finally{store.close();}
});
test('profiles require explicit manual verification, safe URL and preserve original added date',()=>{
 const {store,user}=fixture();try{const r=store.reservations.sync(user,booking());const profile={profileUrl:'https://www.facebook.com/verified-person',profileSource:'Facebook',profileVerifiedManually:true,notes:'Independently verified'};assert.throws(()=>store.reservations.profile(user,r.id,{...profile,profileVerifiedManually:false}),/personally verified/);const saved=store.reservations.profile(user,r.id,profile);assert.ok(saved.guest.profileAddedAt);assert.equal(saved.guest.profileVerifiedManually,true);const sync=store.reservations.sync(user,booking({sourceUpdatedAt:'2026-09-03T00:00:00Z'}));assert.equal(sync.guest.profileUrl,profile.profileUrl);assert.equal(sync.guest.profileAddedAt,saved.guest.profileAddedAt);assert.equal(store.reservations.profile(user,r.id,{...profile,profileUrl:''}).guest.profileVerifiedManually,false);for(const url of ['javascript:alert(1)','data:text/html,test','http://example.com','https://user:pass@example.com'])assert.throws(()=>safeExternalUrl(url));}finally{store.close();}
});
test('reservation API enforces ownership/property access for import, detail, profile and analytics',async()=>{
 const {store,user}=fixture();store.createUser('other@example.test','a-long-test-password',{id:'other',name:'Other'});const r=store.reservations.sync(user,booking());const server=createApi(store);await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base=`http://127.0.0.1:${server.address().port}`;
 const call=(path,token,method='GET',data)=>fetch(base+path,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:data?JSON.stringify(data):undefined});
 try{assert.equal((await call('/api/reservations')).status,401);const login=await(await call('/api/login',null,'POST',{email:'other@example.test',password:'a-long-test-password'})).json();const token=login.token;assert.deepEqual(await(await call('/api/reservations',token)).json(),[]);assert.equal((await call('/api/reservations/'+r.id,token)).status,404);assert.equal((await call('/api/reservations/'+r.id+'/counts',token,'PUT',{adults:9})).status,404);assert.equal((await call('/api/reservations/'+r.id+'/profile',token,'PUT',{})).status,404);assert.equal((await call('/api/reservations/import',token,'POST',booking())).status,403);assert.equal((await call('/api/reservations/analytics?month=2026-09&propertyId=tiger-blvd-516',token)).status,403);}finally{await new Promise(resolve=>server.close(resolve));store.close();}
});
