import React, { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Feather } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useWork } from '../work/WorkProvider';

import { today } from '../mileage';
import { monthlyAnalytics, nights, effectiveCounts } from './domain';
import { calendarWeeks, shiftMonth } from './calendar';
import ReservationDetails from './ReservationDetails';

const channelColor = (source:string) => source.toLowerCase()==='airbnb'?'#a74648':source.toLowerCase()==='vrbo'?'#3a6496':'#294e3b';
export default function OccupancyCalendar(){const work=useWork();return <CalendarContent key={work.signedIn?'owner':'guest'}/>;}
function CalendarContent(){
  const work=useWork();const [month,setMonth]=useState(today().slice(0,7));const [selectedDate,setSelectedDate]=useState('');const [selectedId,setSelectedId]=useState('');
  const bookings=work.signedIn?work.reservations.filter(r=>r.source.propertyId===work.currentProperty.id&&r.source.status==='confirmed'):[];
  const weeks=calendarWeeks(month,bookings,work.currentProperty.id);const summary=monthlyAnalytics(bookings,month,work.currentProperty.id);
  const selected=bookings.find(r=>r.id===selectedId);const dayBookings=bookings.filter(r=>r.source.checkIn<=selectedDate&&r.source.checkOut>=selectedDate);
  const move=(amount:number)=>{setMonth(shiftMonth(month,amount));setSelectedDate('');setSelectedId('');};
  const monthName=new Date(month+'-01T12:00:00').toLocaleDateString('en-US',{month:'long',year:'numeric'});
  return <View style={s.card}>
    <View style={s.header}><View><Text accessibilityRole="header" style={s.title}>Occupancy</Text><Text style={s.muted}>{work.currentProperty.name} · Nightly stay overview{work.demo?' · Sample data':''}</Text></View><Pressable accessibilityRole="button" onPress={()=>router.push('/reservations')} style={s.action}><Text style={s.link}>All reservations ↗</Text></Pressable></View>
    <View style={s.header}><View style={s.controls}><Pressable accessibilityRole="button" accessibilityLabel="Previous occupancy month" disabled={month==='1900-01'} onPress={()=>move(-1)} style={s.action}><Feather name="chevron-left" size={22}/></Pressable><Text accessibilityRole="header" style={s.month}>{monthName}</Text><Pressable accessibilityRole="button" accessibilityLabel="Next occupancy month" disabled={month==='2199-12'} onPress={()=>move(1)} style={s.action}><Feather name="chevron-right" size={22}/></Pressable></View><Pressable accessibilityRole="button" onPress={()=>{setMonth(today().slice(0,7));setSelectedDate(today());setSelectedId('');}} style={s.action}><Text style={s.link}>Today</Text></Pressable></View>
    <Text style={s.muted}>{work.signedIn?`${work.demo?'Demo · ':''}${summary.occupiedPropertyNights} booked nights · ${summary.stays} stays · ${summary.turnovers} departures`:'Sign in or show demo data to load stays. Bookings stay on this device — Airbnb/Vrbo are not linked.'}</Text>
    <View style={s.grid}>
      <View style={s.weekdays}>{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(day=><Text key={day} style={s.weekday}>{day}</Text>)}</View>
      {weeks.map(week=><View key={week.dates[0]} style={{height:Math.max(90,44+week.lanes*44),position:'relative'}}>
        <View style={StyleSheet.absoluteFill}>{<View style={{flex:1,flexDirection:'row'}}>{week.dates.map(date=>{
          const inMonth=date.startsWith(month);const occupied=bookings.filter(r=>r.source.checkIn<=date&&r.source.checkOut>date).length;
          return <Pressable key={date} accessibilityRole="button" accessibilityLabel={`${date}, ${occupied} booked stays`} accessibilityState={{selected:selectedDate===date,disabled:!inMonth}} disabled={!inMonth} onPress={()=>{setSelectedDate(date);setSelectedId('');}} style={[s.day,!inMonth&&s.outside,selectedDate===date&&s.selectedDay]}><Text style={[s.date,date===today()&&s.today,!inMonth&&{color:'#a8afa3'}]}>{Number(date.slice(-2))}</Text></Pressable>;
        })}</View>}</View>
        {week.bars.map(bar=><Pressable key={bar.reservation.id} accessibilityRole="button" accessibilityState={{selected:selectedId===bar.reservation.id}} accessibilityLabel={`${bar.reservation.guest.displayName}, ${effectiveCounts(bar.reservation).totalHumanGuests ?? 'unknown'} guests, ${bar.reservation.source.source}, ${bar.reservation.source.checkIn} to ${bar.reservation.source.checkOut}, ${nights(bar.reservation.source.checkIn,bar.reservation.source.checkOut)} nights`} onPress={()=>{setSelectedId(bar.reservation.id);setSelectedDate('');}} style={[s.stay,{left:`${bar.column/7*100}%`,width:`${bar.span/7*100}%`,top:40+bar.lane*44,backgroundColor:channelColor(bar.reservation.source.source),borderTopLeftRadius:bar.continuesBefore?0:8,borderBottomLeftRadius:bar.continuesBefore?0:8,borderTopRightRadius:bar.continuesAfter?0:8,borderBottomRightRadius:bar.continuesAfter?0:8},selectedId===bar.reservation.id&&s.selectedStay,!!selectedId&&selectedId!==bar.reservation.id&&s.dimStay]}><View style={{flexDirection:'row',alignItems:'center',gap:4}}><Text numberOfLines={1} style={[s.stayName,{flex:1}]}>{bar.continuesBefore?'‹ ':''}{bar.reservation.guest.displayName}{bar.continuesAfter?' ›':''}</Text><View style={{flexDirection:'row',alignItems:'center',gap:2}}><Feather name="users" size={10} color="white"/><Text style={s.stayName}>{effectiveCounts(bar.reservation).totalHumanGuests ?? '?'}</Text></View></View><Text numberOfLines={1} style={s.stayLabel}>{bar.reservation.source.source} · {nights(bar.reservation.source.checkIn,bar.reservation.source.checkOut)} nights</Text></Pressable>)}
      </View>)}
    </View>
    <View style={s.legend}>{['Airbnb','Vrbo','Other'].map(channel=><View key={channel} style={s.controls}><View style={[s.dot,{backgroundColor:channelColor(channel)}]}/><Text style={s.muted}>{channel}</Text></View>)}</View>
    <Text style={s.muted}>Bars cover booked nights; checkout day is not an overnight stay. Blank days mean no imported stay, not confirmed availability.</Text>
    {!!work.error&&<Text style={s.error}>{work.error}</Text>}
    {!!selectedDate&&<View style={s.selection}><Text style={s.month}>{new Date(selectedDate+'T12:00:00').toLocaleDateString('en-US',{weekday:'long',month:'short',day:'numeric'})}</Text>{dayBookings.length?dayBookings.map(r=><Pressable accessibilityRole="button" accessibilityState={{selected:selectedId===r.id}} key={r.id} onPress={()=>setSelectedId(r.id)} style={[s.dayBooking,selectedId===r.id&&s.selectedBooking]}><Text style={s.link}>{r.guest.displayName} · {effectiveCounts(r).totalHumanGuests ?? 'Unknown'} guests</Text><Text style={s.muted}>{r.source.checkIn===selectedDate?'Arriving':r.source.checkOut===selectedDate?'Departing':'Staying overnight'} · {r.source.source} · {r.source.checkIn}–{r.source.checkOut}</Text></Pressable>):<Text style={s.muted}>{work.signedIn?(work.demo?'No demo arrivals, departures or stays for this day.':'No imported arrivals, departures or stays for this day.'):'Sign in or show demo data to view reservation details.'}</Text>}</View>}
    {selected&&<View><Pressable accessibilityRole="button" onPress={()=>setSelectedId('')} style={s.action}><Text style={s.link}>Close stay details</Text></Pressable><ReservationDetails key={selected.id} reservation={selected}/></View>}
  </View>;
}
const s=StyleSheet.create({card:{backgroundColor:'white',padding:16,borderRadius:18,borderWidth:1,borderColor:'#e4e9dc',marginTop:16,gap:12},header:{flexDirection:'row',flexWrap:'wrap',justifyContent:'space-between',alignItems:'center',gap:8},title:{fontSize:22,fontWeight:'600',color:'#294e3b'},month:{fontSize:16,fontWeight:'600',color:'#294e3b'},muted:{fontSize:11,lineHeight:17,color:'#66735e'},link:{color:'#294e3b',fontSize:13,fontWeight:'600'},action:{minHeight:44,padding:10,justifyContent:'center',alignItems:'center'},controls:{flexDirection:'row',alignItems:'center',gap:6},grid:{borderWidth:1,borderColor:'#e4e9dc',borderRadius:12,overflow:'hidden'},weekdays:{flexDirection:'row',backgroundColor:'#f7f8f2',paddingVertical:10},weekday:{width:'14.2857%',textAlign:'center',fontSize:11,color:'#66735e'},day:{flex:1,borderTopWidth:1,borderRightWidth:1,borderColor:'#e4e9dc',paddingTop:6,alignItems:'center'},outside:{backgroundColor:'#f5f6f1'},selectedDay:{backgroundColor:'#e5efdf'},date:{fontSize:12,color:'#294e3b',width:28,height:28,textAlign:'center',lineHeight:28},today:{backgroundColor:'#294e3b',color:'white',borderRadius:14},stay:{position:'absolute',minHeight:40,paddingHorizontal:5,paddingVertical:4,borderLeftWidth:2,borderRightWidth:2,borderColor:'white'},stayName:{fontSize:11,fontWeight:'600',color:'white'},stayLabel:{fontSize:9,color:'#ffffffdd',marginTop:2},legend:{flexDirection:'row',gap:18,flexWrap:'wrap'},dot:{width:9,height:9,borderRadius:5},selection:{gap:8,borderTopWidth:1,borderColor:'#e4e9dc',paddingTop:14},dayBooking:{padding:12,backgroundColor:'#f7f8f2',borderRadius:10,gap:4,borderWidth:2,borderColor:'transparent'},selectedBooking:{backgroundColor:'#e5efdf',borderColor:'#294e3b'},selectedStay:{borderColor:'#f0d878',borderWidth:3,shadowColor:'#152b22',shadowOpacity:0.35,shadowRadius:6,shadowOffset:{width:0,height:2},elevation:4,zIndex:2},dimStay:{opacity:0.45},error:{color:'#a33f30',fontSize:12}});



