import React, { useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { Picker } from '@react-native-picker/picker';
import TripDateField from '../TripDateField';
import { duration, hours, exactTime, newWorkDraft, validateWork, WORK_TYPES, type WorkDraft, type WorkEntry } from './domain';
import { useWork } from './WorkProvider';

export const s=StyleSheet.create({card:{backgroundColor:'white',borderColor:'#e4e9dc',borderWidth:1,borderRadius:18,padding:20,gap:12,marginTop:18},title:{fontSize:22,fontWeight:'600',color:'#294e3b'},text:{fontSize:14,color:'#3d543b',lineHeight:21},muted:{fontSize:12,color:'#66735e',lineHeight:19},row:{flexDirection:'row',flexWrap:'wrap',gap:12,alignItems:'center'},input:{borderWidth:1,borderColor:'#cbd6c3',borderRadius:10,padding:12,minHeight:48,color:'#294e3b',backgroundColor:'#fafbf7',fontSize:15},button:{minHeight:48,paddingHorizontal:16,paddingVertical:13,borderRadius:10,backgroundColor:'#294e3b',justifyContent:'center',alignItems:'center'},buttonText:{color:'white',fontWeight:'600'},error:{color:'#a33f30',fontSize:13,lineHeight:20},label:{fontWeight:'600',color:'#3d543b',marginBottom:6},section:{gap:12},metric:{flex:1,minWidth:90,padding:12,backgroundColor:'#edf1e4',borderRadius:12},page:{padding:22,paddingBottom:60,maxWidth:1050,width:'100%',alignSelf:'center',gap:12}});
export function Button({title,onPress,disabled=false}:{title:string;onPress:()=>void;disabled?:boolean}){return <Pressable accessibilityRole="button" accessibilityState={{disabled}} disabled={disabled} onPress={onPress} style={[s.button,disabled&&{opacity:0.5}]}><Text style={s.buttonText}>{title}</Text></Pressable>;}
export function Input({label,value,onChange,multiline=false,placeholder='',password=false}:{label:string;value:string;onChange:(s:string)=>void;multiline?:boolean;placeholder?:string;password?:boolean}){return <View style={{flexGrow:1}}><Text style={s.label}>{label}</Text><TextInput accessibilityLabel={label} value={value} onChangeText={onChange} multiline={multiline} secureTextEntry={password} autoCapitalize="none" placeholder={placeholder} style={[s.input,multiline&&{minHeight:90,textAlignVertical:'top'}]}/></View>;}
export function Select({label,value,onChange,options}:{label:string;value:string;onChange:(s:string)=>void;options:{label:string;value:string}[]}){return <View><Text style={s.label}>{label}</Text><Picker accessibilityLabel={label} selectedValue={value} onValueChange={onChange} style={s.input}>{options.map(o=><Picker.Item key={o.value} label={o.label} value={o.value}/>)}</Picker></View>;}
export function Account(){const work=useWork();const[email,setEmail]=useState('');const[password,setPassword]=useState('');return <View style={s.section}><Text style={s.text}>{work.status?.needsSetup?'Create your owner account to save Work Log records.':'Sign in to access your saved Work Log records.'}</Text><Input label="Owner email" value={email} onChange={setEmail}/><Input label="Password" value={password} onChange={setPassword} password/><Text style={s.muted}>First setup: use at least 12 characters. Sessions last 12 hours and sign out when the app restarts. Work records stay in the server database.</Text>{!!work.error&&<Text accessibilityRole="alert" style={s.error}>{work.error}</Text>}<Button title={work.busy?'Connecting…':work.status?.needsSetup?'Create owner account':'Sign in'} disabled={work.busy||!work.status||(work.status.needsSetup&&!work.status.canSetup)} onPress={()=>{void work.login(email,password).then(()=>setPassword('')).catch(()=>{});}}/><Button title="Retry connection" disabled={work.busy||work.demo} onPress={()=>{void work.check();}}/></View>;}
export function WorkForm({initial,onSave,onCancel}:{initial?:WorkDraft;onSave:(d:WorkDraft)=>Promise<void>;onCancel?:()=>void}){
 const work=useWork();const[draft,setDraft]=useState(()=>initial||newWorkDraft(work.properties[0]?.id));const[message,setMessage]=useState('');const[error,setError]=useState('');
 const change=(key:keyof WorkDraft,value:string)=>{setDraft(d=>({...d,[key]:value}));setMessage('');setError('');};let preview='';try{preview=`${hours(duration(draft))} hours · ${exactTime(duration(draft))}`;}catch{}
 return <View style={s.section}><TripDateField label="Work date" value={draft.workDate} onChange={v=>change('workDate',v)} disabled={work.busy||work.demo}/><View style={s.row}>{(['times','hours'] as const).map(mode=><Pressable key={mode} accessibilityRole="radio" accessibilityState={{checked:draft.entryMethod===mode}} onPress={()=>change('entryMethod',mode)} style={[s.button,{backgroundColor:draft.entryMethod===mode?'#294e3b':'#edf1e4'}]}><Text style={{color:draft.entryMethod===mode?'white':'#294e3b'}}>{mode==='times'?'Start / End Time':'Enter Hours'}</Text></Pressable>)}</View>{draft.entryMethod==='times'?<View style={s.row}><Input label="Start time" placeholder="08:00" value={draft.startTime} onChange={v=>change('startTime',v)}/><Input label="End time" placeholder="11:30" value={draft.endTime} onChange={v=>change('endTime',v)}/><Text style={s.muted}>24-hour time · 13:00 = 1 PM</Text></View>:<Input label="Hours worked" placeholder="1.75" value={draft.hours} onChange={v=>change('hours',v)}/>}<Text style={s.text}>{preview||'Enter your work duration.'}</Text><Select label="Property" value={draft.propertyId} onChange={v=>change('propertyId',v)} options={work.properties.map(p=>({value:p.id,label:p.name}))}/><Select label="Work type" value={draft.workType} onChange={v=>change('workType',v)} options={WORK_TYPES.map(t=>({value:t,label:t}))}/><Input label="What was done?" multiline value={draft.description} onChange={v=>change('description',v)}/>{!!error&&<Text accessibilityRole="alert" style={s.error}>{error}</Text>}{!!message&&<Text accessibilityLiveRegion="polite" style={s.text}>{message}</Text>}<View style={s.row}><Button title={work.busy?'Saving…':initial?'Save changes':'Add Work Log'} disabled={work.busy||work.demo} onPress={()=>{void(async()=>{try{validateWork(draft);await onSave(draft);if(!initial)setDraft({...newWorkDraft(draft.propertyId),workType:draft.workType});setMessage('Work log saved.');setError('');}catch(e){setError((e as Error).message);}})();}}/>{onCancel&&<Button title="Cancel edit" disabled={work.busy||work.demo} onPress={onCancel}/>}</View></View>;
}
export function EntryCard({entry,onEdit}:{entry:WorkEntry;onEdit:(e:WorkEntry)=>void}){const work=useWork();const[confirm,setConfirm]=useState(false);return <View style={s.card}><View style={s.row}><Text style={s.label}>{entry.workDate}</Text><Text style={s.text}>{entry.startTime?`${entry.startTime}–${entry.endTime}`:'—'}</Text><Text style={s.label}>{hours(entry.minutesWorked)} hrs</Text></View><Text style={s.text}>{entry.description}</Text><Text style={s.muted}>{entry.workType} · {work.properties.find(p=>p.id===entry.propertyId)?.name} · {exactTime(entry.minutesWorked)}</Text>{confirm?<View style={s.section}><Text style={s.error}>Delete this work log entry permanently?</Text><View style={s.row}><Button title="Cancel deletion" onPress={()=>setConfirm(false)}/><Button title="Confirm delete" disabled={work.busy||work.demo} onPress={()=>{void work.remove(entry.id).catch(()=>{});}}/></View></View>:<View style={s.row}><Button title="Edit" disabled={work.busy||work.demo} onPress={()=>onEdit(entry)}/><Button title="Delete" disabled={work.busy||work.demo} onPress={()=>setConfirm(true)}/></View>}</View>;}


